project_id = "uoyzfzzjzhvcxfmpmufz"

[functions.create-default-users]
verify_jwt = true

[functions.import-csv]
verify_jwt = true

[functions.corrigir-paridade]
verify_jwt = true

[functions.importar-excel-lote]
verify_jwt = true

[functions.processar-forms-webhook]
verify_jwt = true

[functions.importar-csv-lote]
verify_jwt = true
